
<<DOCHISTORY>>
/*-------------------------------------------------------------------------------------------------*/
/* Copyright Luminary Solutions Limited                                                            */
/*-------------------------------------------------------------------------------------------------*/
/*-------------------------------------------------------------------------------------------------*/
/*                                                                                                 */
/* Template:       : Depopulator.tpl                                                               */
/*                                                                                                 */
/* Template Name   : OpenROAD Class Proxy Template                                                 */
/*                                                                                                 */
/* System Name     : ProxyGen                                                                      */
/*                                                                                                 */
/* Sub-System Name : PDO depopulator                                                               */
/*                                                                                                 */
/* Author          : Luminary - An Ingres Company                                                  */
/*                                                                                                 */
/* Date            : 10/06/2008                                                                    */
/*                                                                                                 */
/* Description     : Used to depopulate PDOs                                                       */
/*                                                                                                 */
/* Version History                                                                                 */
/*                                                                                                 */
/* Version Date     Who   Description                                                              */
/* ------- -------- ----- -----------                                                              */
/* 1.0     10/06/08 LUM   Original version.                                                        */
/*-------------------------------------------------------------------------------------------------*/
<<DOCHISTORY>>
#region Copyright
/*
 * Copyright ${copyright_holder}
 *
 */
#endregion

#region Code Header
/*
 * Author               : Generated By ProxyGen (Luminary Solutions)
 *
 * File Name            : ${AppService Name}Depopulator.cs
 *
 * Description          : Generated by ProxyGen from the ${AppService Name} Application Service.
 *                        This code should not be modified.
 *
 * Version History
 *
 * Version  Date                 Who     Description
 * -------  ----------           ---     --------------
 * 1.0      ${datenow}           ${username}     Original Generated Version.
 */
#endregion

#region Namespaces Used
using System;
using System.Data;
using ORRSOLib;
using Luminary.ProxyGen.Util;
using ${namespace_prefix}.DTO;
#endregion

namespace ${namespace_prefix}.ApplicationServices.Wrappers
{
    public class ${AppService Name}Depopulator
    {
        #region Properties
        #endregion

        #region Class Methods
<<FOREACHCLASS>>
<<!NAME=>>(core!uc_osca)(core!uc_xml_include)(core!uc_client_info)
        /// <summary>
        /// DepopulatePDOToObject
        /// </summary>
        /// <param name="pdo">PDO to depopulate from.</param>
        /// <param name="attributeName">The Attribute name within the PDO.</param>
        /// <param name="${class_prefix}${class_langname}*DTO*">The Data Transport Object to depopulate the PDO into.</param>
        public static void DepopulatePDOToObject(ORPDOClass pdo, String name, *U*${class_prefix}${class_langname} *L*${class_prefix}${class_langname}*DTO* )
        {
            int rows;
<<FOREACHATTR>>
<<SCALAR>>
<<!NULLABLE>>
            *L*${class_prefix}${class_langname}*DTO*.*U*${langname} = AttributeManager.Get${access}Attribute(pdo, name + ".${name}");
<<!NULLABLE>>
<<NULLABLE>>
            You have a nullable scalar. Do you want nullable scalars?
<<NULLABLE>>
<<SCALAR>>
<<CLASS>>
            DepopulatePDOToObject(pdo, name + ".${name}", *L*${class_prefix}${class_langname}*DTO*.*U*${langname}*Class*);
<<CLASS>>
<<!DEFINED>>(${list})
<<ARRAY>>
            *L*${class_prefix}${class_langname}*DTO*.*U*${langname}*List*.Clear();
            rows = pdo.LastRow( name + ".${name}" );
            for( int i=1; i<=rows; i++)
            {
               *U*${type} ob = new *U*${type}();

                DepopulatePDOToObject(pdo, name + ".${name}[" + i + "]", ob);
                *L*${class_prefix}${class_langname}*DTO*.*U*${langname}*List*.Add(ob);
            }
<<ARRAY>>
<<!DEFINED>>(${list})
<<DEFINED>>(${list})
<<ARRAY>>
            *L*${class_prefix}${class_langname}*DTO*.Clear();
            rows = pdo.LastRow( name + ".${name}");
            for ( int i=1; i<=rows; i++)
            {
                ${list} ob = new ${list}();
                DepopulatePDOToObject(pdo, name + ".${name}[" + i + "]", ob);
                *L*${class_prefix}${class_langname}*DTO*.Add(ob);
            }
<<ARRAY>>
<<DEFINED>>(${list})
<<FOREACHATTR>>
        }

<<!NAME=>>(core!uc_osca)(core!uc_xml_include)(core!uc_client_info)
<<FOREACHCLASS>>
        #endregion
    }
}
