
<<DOCHISTORY>>
/*-------------------------------------------------------------------------------------------------*/
/* Copyright Luminary Solutions Limited                                                            */
/*-------------------------------------------------------------------------------------------------*/
/*-------------------------------------------------------------------------------------------------*/
/*                                                                                                 */
/* Template:       : DTCGen.tpl                                                                    */
/*                                                                                                 */
/* Template Name   : OpenROAD Class Proxy Template                                                 */
/*                                                                                                 */
/* System Name     : ProxyGen                                                                      */
/*                                                                                                 */
/* Sub-System Name : User Class proxy                                                              */
/*                                                                                                 */
/* Author          : Luminary - An Ingres Company                                                  */
/*                                                                                                 */
/* Date            : 10/06/2008                                                                    */
/*                                                                                                 */
/* Description     : Used to generate a proxy wrapper for an OpenROAD class                        */
/*                                                                                                 */
/* Version History                                                                                 */
/*                                                                                                 */
/* Version Date     Who   Description                                                              */
/* ------- -------- ----- -----------                                                              */
/* 1.0     10/06/08 LUM   Original version.                                                        */
/*-------------------------------------------------------------------------------------------------*/
<<DOCHISTORY>>
#region Copyright
/*
 * Copyright ${copyright_holder}
 *
 */
#endregion

#region Code Header
/*
 * Author               : Generated By ProxyGen (Luminary Solutions)
 *
 * File Name            : *U*${class_langname}.cs
 *
 * Description          : Generated by ProxyGen from the ${AppService Name} Application Service.
 *                        This code should not be modified.
 *
 * Version History
 *
 * Version  Date                 Who     Description
 * -------  ----------           ---     --------------
 * 1.0      ${datenow}           ${username}     Original Generated Version.
 */
#endregion

#region Namespaces Used
using System;
using System.Collections.Generic;
using System.Text;
#endregion

namespace ${namespace_prefix}.DTO
{
    /// <summary>
    /// ${class_langname} Class
    /// </summary>
<<DEFINED>>(${list})
    public class *U*${class_langname} : List<${list}>
<<DEFINED>>(${list})
<<!DEFINED>>(${list})
    public class *U*${class_langname}
<<!DEFINED>>(${list})
    {
        #region Fields
<<FOREACHATTR>>
<<SCALAR>>
<<!NULLABLE>>
<<ONLYIF>><<STRING>>
        private ${type} ${type_prefix}*L*${langname} = "${default_value}";
<<ONLYIF>><<STRING>>
<<ONLYIF>><<FLOAT>><<BYTE>><<DOUBLE>><<SHORT>><<DECIMAL>><<INT>><<MONEY>><<DATETIME>>
        private ${type} ${type_prefix}*L*${langname} = ${default_value};
<<ONLYIF>><<FLOAT>><<BYTE>><<DOUBLE>><<SHORT>><<DECIMAL>><<INT>><<MONEY>><<DATETIME>>
<<!NULLABLE>>
<<NULLABLE>>
        There's a nullable scalar in this class. Is that what you want?
<<NULLABLE>>
<<SCALAR>>
<<CLASS>>
<<!DV_NULL>>
        private *U*${type} ${type_prefix}*L*${langname}*Class* = new *U*${type}();
<<!DV_NULL>>
<<DV_NULL>>
        private *U*${type} ${type_prefix}*L*${langname}*Class* = null;
<<DV_NULL>>
<<CLASS>>
<<!DEFINED>>(${list})
<<ARRAY>>
<<!DV_NULL>>
        private List<*U*${type}> ${type_prefix}*L*${langname}*List* = new List<*U*${type}>();
<<!DV_NULL>>
<<DV_NULL>>
        private List<*U*${type}> ${type_prefix}*L*${langname}*List* = null;
<<DV_NULL>>
<<ARRAY>>
<<!DEFINED>>(${list})
<<FOREACHATTR>>
        #endregion Fields

        #region Properties
<<FOREACHATTR>>
<<SCALAR>>

        public ${type} *U*${langname}
        {
            get
            {
                return ${type_prefix}*L*${langname};
            }
            set
            {
                ${type_prefix}*L*${langname} = value;
            }
        }
<<SCALAR>>
<<CLASS>>

        public *U*${type} *U*${langname}*Class*
        {
            get
            {
                return ${type_prefix}*L*${langname}*Class*;
            }
            set
            {
                ${type_prefix}*L*${langname}*Class* = value;
            }
        }
<<CLASS>>
<<!DEFINED>>(${list})
<<ARRAY>>

        public List<*U*${type}> *U*${langname}*List*
        {
            get
            {
                return ${type_prefix}*L*${langname}*List*;
            }
            set
            {
                ${type_prefix}*L*${langname}*List* = value;
            }
        }
<<ARRAY>>
<<!DEFINED>>(${list})

<<FOREACHATTR>>
        #endregion Properties
    }
}
